### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by birdybro** [GX400-Friends/gx400-bin#6]
Hi, when will the source code be made available for this core?

Thanks!

**Comment by atrac17** [comment]
> Hi, when will the source code be made available for this core?
> 
> Thanks!

Would you like me to send you a copy? WHAT DOES THIS SOURCE CODE DO????

**Comment by suverman** [comment]
lol he wants it so he hacks it pretend he is a dev. Brilliant.

**Comment by birdybro** [comment]
Someone asked me about it because the framework seemed to be outdated. I was considering contributing to it to get the framework updated, but was unable to since the source is available. Had I known you two were involved I never would have opened the issue.
